<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <!-- 父项目配置 一般不需要更改 -->
    <parent>
        <artifactId>parent</artifactId>
        <groupId>io.obase</groupId>
        <version>1.0.0</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <!-- 当前模块的打包配置 -->
    <artifactId>providers.sqlserver</artifactId>
    <packaging>jar</packaging>
    <version>${packageVersion}</version>

    <!-- 添加模块描述 -->
    <name>Obase Providers SqlServer</name>
    <description>适用于SqlServer数据库的Obase存储提供程序中间件</description>

    <!-- 具体依赖配置 -->
    <dependencies>
        <!-- 引用Obase sql库  -->
        <dependency>
            <groupId>io.obase</groupId>
            <artifactId>providers.sql</artifactId>
            <version>${packageVersion}</version>
        </dependency>
        <!-- SqlServer JDBC驱动 版本号于父项目指定 -->
        <dependency>
            <groupId>com.microsoft.sqlserver</groupId>
            <artifactId>mssql-jdbc</artifactId>
            <version>12.2.0.jre8</version>
        </dependency>
    </dependencies>
</project>