<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <!-- 父项目配置 一般不需要更改 -->
    <parent>
        <artifactId>unit-test</artifactId>
        <groupId>io.obase</groupId>
        <version>1.0.0</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <!-- 当前模块的打包配置 -->
    <artifactId>addon-test-domain</artifactId>
    <version>${packageVersion}</version>

    <!-- 具体依赖配置 -->
    <dependencies>
        <!-- 引用Obase 逻辑删除库  -->
        <dependency>
            <groupId>io.obase</groupId>
            <artifactId>logical.deletion</artifactId>
            <version>${packageVersion}</version>
        </dependency>
        <!-- 引用Obase 多租户库  -->
        <dependency>
            <groupId>io.obase</groupId>
            <artifactId>multi.tenant</artifactId>
            <version>${packageVersion}</version>
        </dependency>
        <!-- 引用Obase 标注建模库  -->
        <dependency>
            <groupId>io.obase</groupId>
            <artifactId>odm.annotation</artifactId>
            <version>${packageVersion}</version>
        </dependency>
    </dependencies>
</project>