<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <!-- 父项目配置 一般不需要更改 -->
    <parent>
        <artifactId>unit-test</artifactId>
        <groupId>io.obase</groupId>
        <version>1.0.0</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <!-- 当前模块的打包配置 -->
    <artifactId>test</artifactId>
    <version>${packageVersion}</version>

    <dependencies>
        <!-- junit 单元测试  -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
        </dependency>
        <!-- slf4j 日志 -->
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
        </dependency>
        <!-- 引用单元测试的基础设施 -->
        <dependency>
            <groupId>io.obase</groupId>
            <artifactId>test-infrastructure</artifactId>
            <version>${packageVersion}</version>
        </dependency>
    </dependencies>

</project>